### ISSUE TITLE
Some questions for usage

### ISSUE THREAD

**Issue by amargautam** [justinm/grape_devise#3]
1. Is this up to date with latest grape and ruby 2.4
2. Does all devise functions work like registration/ email confirmation etc? What are the endpoints?
3. How to implement token authorization using this gem?

**Comment by justinm** [comment]
1. It's been awhile since I worked on a Rails project, but as far as I know this should still be compatible with newer versions.
2. This library acts as a bridge between Devise and Grape, so any options available for Devise should work.
3. I've not implemented token authentication in Rails so I wouldn't be the best to answer this question. However, a quick google search indicates there may be some libraries out there to allow Devise to support token authentication.

My best advice is always to try it and see if it works for you. If you find any issues feel free to report them. Also, PRs are always welcome and I try to be timely with getting them merged in.

**Comment by amargautam** [comment]
I myself is not working on rails. I am using grape as a standalone app to serve rest apis. I couldn't find a ready to go implementation for proper authentication via token so finally I had to write my own. Also some of the token gems available today use active record. I am using mongoid. 

Finally I used jwt for token generation. It is very easy to set up and works like a charm on multiple devices at once. I am using treating the token as a session object without actually keeping the whole thing stateless. Working fine for me. You can close this issue.

**Comment by justinm** [comment]
Sorry about the Rails reference, I should have said Ruby. I'm glad you figured it out. Feel free to post a gist in case someone else may come across this issue.

Thanks!  Closing.
